activation: silu
adaptive_rounds: 6
add_af2_pairwise: false
add_af2_single: false
add_confidence: false
add_conservation: false
add_dssp: true
add_msa: false
add_msa_contacts: true
add_plddt: true
add_position: true
add_ptm: false
add_sidechain: true
alt_projector: 65
alt_type: concat
attn_activation: silu
batch_size: 10
computed_graph: true
contrastive_loss_fn: null
convert_to_onesite: false
cutoff_lower: 0.0
cutoff_upper: 36.0
data_augment: false
data_file_test: ./data.files/ThermoMPNN.turing/testing.csv
data_file_train: ./data.files/ThermoMPNN.turing/training.csv
data_file_train_ddp_prefix: ./data.files/ThermoMPNN.turing/training
data_split_fn: ''
data_type: ThermoMPNN
dataset: GraphMutationDataset
distance_influence: both
drop_out: 0.6
ee_channels: null
freeze_representation: false
freeze_representation_but_attention: false
freeze_representation_but_gru: false
gpu_id: 0
graph_type: af2
hp_tune: false
init_fn: null
interpret_by: null
interpret_epoch: null
interpret_idxes: null
interpret_step: null
load_model: null
loaded_af2_pairwise: false
loaded_af2_single: false
loaded_confidence: false
loaded_esm: false
loaded_msa: false
log_dir: ./PreMode.results/PreMode.noESM.noMSA/
loop: true
loss_fn: mse_loss
lr: 1e-4
lr_factor: 0.8
lr_min: 1e-6
lr_patience: 2
lr_warmup_steps: 4000
max_len: 251
max_num_neighbors: 36
mode: train
model: equivariant-transformer-star2-softmax
model_class: PreMode_Star_CON
neighbor_embedding: true
neighbor_type: KNN
ngpus: 4
node_embedding_type: one-hot
num_edge_attr: 2
num_epochs: 40
num_heads: 16
num_layers: 2
num_nodes: 1
num_rbf: 32
num_save_batches: 400
num_save_epochs: 1
num_steps_update: 8
num_workers: 0
out_dir: null
output_dim: 1
output_dim_1: 1
output_dim_2: 1
output_model: EquivariantBinaryClassificationStarPoolScalar
partial_load_model: false
radius: 50
rbf_type: expnormunlim
re_test: false
reduce_op: mean
reset_train_dataloader_each_epoch: true
reset_train_dataloader_each_epoch_seed: false
save_attn: false
scale_plddt: false
score_transfer: false
seed: 0
seed_with_pl: false
share_kv: false
test_by: epoch_and_batch
test_size: null
train_size: 0.95
trainable_rbf: true
trainer_fn: PreMode_trainer
triangular_update: true
use_cb: true
use_ig: false
use_jacob: false
use_lmdb: false
use_lora: null
use_output_head: false
val_size: 0.05
vec_channels: 32
vec_hidden_channels: 512
vec_in_channels: 35
weight_decay: 0.0
x_channels: 512
x_hidden_channels: 512
x_in_channels: 39
x_in_embedding_type: Linear_gelu
y_weight: 1.0
zero_msa: false
